### ISSUE TITLE
How to get Theme Roller option to custom style using APEX5.0 theme

### ISSUE THREAD

**Issue by dpccrt87** [iMingLei/APEXnote#2]
Hi @iMingLei,
I used your APEX5.0 Theme 3 months ago, and i get a little trouble:
I can not get the THEME ROLLER from the list of developer toolbar options, to custom style by profile.
So I get something like:
![toolbar](https://user-images.githubusercontent.com/12938748/57134746-fee21300-6d9e-11e9-8bc0-c8ad68e9a69d.PNG)

Thank you for help in advance.

**Comment by iMingLei** [comment]
Hi,

I think it's normal. You need to configure `Theme Roller Attributes` to enable it.

- Follow the path:
Application nnn \ Shared Components \ Themes \ Create / Edit Theme \ Theme Styles
- Put something like below:
![image](https://user-images.githubusercontent.com/4404261/57467952-8a511d80-7251-11e9-98a3-214471c36191.png)
- Then you can see the Theme Roller from Dev ToolBar. However, this theme is only for internal usage and too old to be supported by Theme Roller. 

Maybe you can try to export the latest version from APEX 19.1 using the same way I posted for extracting the theme from apex builder app 4000 and 4550. (Not recommended.) 

But why you want to use this internal theme for your application? It's Ok for study or research but not for real application.

Good Luck.
